name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployed By
        run: echo "${{ github.actor }}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --upgrade pip
          pip3 install awscli
