name: deployment-workflow

on:
  push:
    branches:
      - main

jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: "Print the input username and github actor"
        run: echo "The username is ${{ github.event.inputs.username }} and actor is ${{ github.actor }}"
