name: deployment-workflow

on:
  push:
    branches:
      - main

jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: "Deployed By"
        run: echo "${{ github.actor }}"

      - name: "Git current branch"
        run: git branch --show-current
