name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployed By
        run: echo "${{ github.actor }}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --upgrade pip
          pip3 install awscli

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ variables.AWS_DEFAULT_REGION }}

      - name: Build and Push to S3
        run: |
          npm install
          npm run build
          aws s3 sync build/ s3://myportolio-code
